# Generated by Django 4.1.2 on 2022-11-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
